version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: skorodenko
      POSTGRES_PASSWORD: 1234321
      POSTGRES_DB: contacts
    ports:
      - 5432:5432
